server:
  port: 9014
spring:
  application:
    name: tensquare-article-crawler #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.207.111:3306/tensquare_article?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.207.111
  jpa:
    database: MySQL
    show-sql: true
article:
  url1: https://www.oschina.net/blog?classification=428612