server: 
  port: 9006
spring: 
  application:  
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.207.111
      database: tensquare
      port: 27017
  redis:
    host: 192.168.207.111
    port: 6379

